### ISSUE TITLE
Can I know what your dataset is? 

### ISSUE THREAD

**Issue by wenyang001** [hellloxiaotian/PSLNet#1]

**Comment by wenyang001** [comment]
I saw your paper that said it was from 477 natural images from the PASCAL VOC 2021. However, the number of PASCAL VOC 2021 is much bigger than 477.

**Comment by hellloxiaotian** [comment]
Thank you for your attention. We select 477 images from PASCAL VOC. And we provide the H5 file, which can download from https://pan.baidu.com/s/1JeVPgLlNeG-FAnkAGF37mw (passwd: 7rzo).
